# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # test_browser:

  #   runs-on: ubuntu-latest
  #   env:
  #     browser_directory: ./danfojs-browser

  #   strategy:
  #     matrix:
  #       node-version: [10.x, 12.x, 14.x]

  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Use Node.js ${{ matrix.node-version }}
  #     uses: actions/setup-node@v1
  #     with:
  #       node-version: ${{ matrix.node-version }}
  #   - run: cd danfojs-browser
  #   - run: yarn
  #   - run: yarn test

  test_node:

    runs-on: ubuntu-latest
    env:
       working_directory: ./danfojs-node    

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        working-directory: ${{ env.working_directory }}
    - run: yarn
    - run: yarn test
